version: '3'

tasks:
  test:unit:
    desc: "ユニットテストを実行する（例: task test:unit -- -run TestNewEmail/異常系）"
    cmds:
      - gotestsum --format testname -- -v ./... {{.CLI_ARGS}}

  test:unit:short:
    desc: ユニットテストを実行する（簡易出力）
    cmds:
      - gotestsum -- ./...

  test:integration:
    desc: インテグレーションテストを実行する
    dotenv:
      - .env.testing
    cmds:
      - go test -v -tags=integration ./internal/infrastructure/...

  test:
    desc: 全テストを実行する（ユニット + インテグレーション）
    dotenv:
      - .env.testing
    cmds:
      - gotestsum --format testname -- -v -tags=integration ./...

  fmt:
    desc: コードをフォーマットする
    cmds:
      - gofmt -w .

  vet:
    desc: 静的解析を実行する
    cmds:
      - go vet ./...

  lint:
    desc: golangci-lintで静的解析を実行する
    cmds:
      - mise exec -- golangci-lint run ./...

  lint:fix:
    desc: 自動修正可能な問題を修正する
    cmds:
      - mise exec -- golangci-lint run --fix ./...

  build:
    desc: ビルドする
    cmds:
      - go build -o go-api .

  run:
    desc: サーバーを起動する
    cmds:
      - go run ./cmd/server

  check:
    desc: fmt + vet + test:unit をまとめて実行する
    cmds:
      - task: fmt
      - task: vet
      - task: test:unit

  db:up:
    desc: マイグレーションを実行する
    cmds:
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" up

  db:down:
    desc: マイグレーションをロールバックする
    cmds:
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" down 1

  db:reset:
    desc: DBをリセットする（全てdown→up）
    cmds:
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" drop -f
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" up

  db:create:
    desc: "新しいマイグレーションを作成する（例: task db:create -- create_posts）"
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}

  generate:
    desc: sqlcでコード生成する
    cmds:
      - sqlc generate

  docs:
    desc: ドキュメントサーバーを起動する（http://localhost:6060）
    cmds:
      - pkgsite -http=:6060 .
