version: '3'

tasks:
  test:
    desc: "テストを実行する（例: task test -- -run TestNewEmail/異常系）"
    cmds:
      - gotestsum --format testname -- -v ./... {{.CLI_ARGS}}

  test:short:
    desc: テストを実行する（簡易出力）
    cmds:
      - gotestsum -- ./...

  fmt:
    desc: コードをフォーマットする
    cmds:
      - gofmt -w .

  vet:
    desc: 静的解析を実行する
    cmds:
      - go vet ./...

  build:
    desc: ビルドする
    cmds:
      - go build -o go-api .

  run:
    desc: サーバーを起動する
    cmds:
      - go run main.go

  check:
    desc: fmt + vet + test をまとめて実行する
    cmds:
      - task: fmt
      - task: vet
      - task: test

  db:up:
    desc: マイグレーションを実行する
    cmds:
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" up

  db:down:
    desc: マイグレーションをロールバックする
    cmds:
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" down 1

  db:reset:
    desc: DBをリセットする（全てdown→up）
    cmds:
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" drop -f
      - migrate -path db/migrations -database "postgres://app:password@localhost:5432/go_api?sslmode=disable" up

  db:create:
    desc: "新しいマイグレーションを作成する（例: task db:create -- create_posts）"
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}
